### ISSUE TITLE
Use XML2RFC site for fetching RFC bibliographic data

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#10]
https://github.com/riboseinc/ietfbib/blob/17ebec4daf1db373ee71e632dcac244f6efc6406/lib/ietfbib/scrapper.rb#L13

Why don't we use `https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ids/reference.RFC.nnnn.xml` to fetch XML RFC bibliography instead?

(such as, https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.0001.xml)

Related to: https://github.com/riboseinc/metanorma-standoc/issues/27#issuecomment-443088016

**Comment by andrew2net** [comment]
@ronaldtse I don't remember. Looks like it was able to find RFC documents using `https://www.rfc-editor.org/refs/bibxml/reference.CODE` and I-D using `https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ids/reference.CODE` only. Maybe something changes since there. It uses the same parser for both links, so you can replace `https://www.rfc-editor.org/refs/bibxml/reference.CODE` with `https://xml2rfc.tools.ietf.org/public/rfc/bibxml-ids/reference.RFC.nnnn.xml` and try.

**Comment by ronaldtse** [comment]
@andrew2net thanks. In this case could you help make the change?

**Comment by andrew2net** [comment]
@ronaldtse changed it

**Comment by opoudjis** [comment]
Confirmed.

**Comment by ronaldtse** [comment]
Can we have a release for this? Thanks @opoudjis
